---
ID: "15d7617a-38e0-4040-845f-7e06fab1fd24"
Parent: "6eec8e87-d79b-4be9-b09e-62891791efc6"
Template: "6eec8e87-d79b-4be9-b09e-62891791efc6"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Video and Text Folder/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: office/32x32/movie_camera.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {99E9EFEC-2EEE-4972-A998-48252ADC9E79}
    {6EEC8E87-D79B-4BE9-B09E-62891791EFC6}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "1259fa74-c824-4260-907d-ea4c6361b5e4"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240221T194930Z
