---
ID: "5ea3732a-03b8-4680-a50c-19f251b9d3a9"
Parent: "1554dfc7-9052-447d-86ed-395278198906"
Template: "1554dfc7-9052-447d-86ed-395278198906"
Path: /sitecore/templates/Project/Sugcon2024/Sponsors/SponsorListing Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {B15B6056-C271-490B-972E-405750D7A9E7}
    {1554DFC7-9052-447D-86ED-395278198906}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "41e0ffaa-6a75-438b-a29e-5fb935c62688"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\U0zm6N0Wat
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240228T140752Z
