services:

  # Container used to run the MVP Rendering host.
  mvp-rendering:
    environment:
      Sitecore__InstanceUri: ${EXPERIENCE_EDGE_URL}
      Sitecore__LayoutServicePath: "/api/graphql/v1"
      Sitecore__ExperienceEdgeToken: ${EXPERIENCE_EDGE_TOKEN}

  sugcon-eu:
    environment:
      SITECORE_API_HOST: ${EXPERIENCE_EDGE_URL}
      SITECORE_API_KEY: ${EXPERIENCE_EDGE_TOKEN}
      GRAPH_QL_ENDPOINT: ${GRAPH_QL_ENDPOINT}

  sugcon-anz:
    environment:
      SITECORE_API_HOST: ${EXPERIENCE_EDGE_URL}
      SITECORE_API_KEY: ${EXPERIENCE_EDGE_TOKEN}
      GRAPH_QL_ENDPOINT: ${GRAPH_QL_ENDPOINT}

  # Scale all containers down 0 to just run hosts & treafik
  mssql:
    scale: 0
  solr:
    scale: 0
  cm:
    scale: 0
  mssql-init:
    scale: 0
  solr-init:
    scale: 0