---
ID: "b1a08f16-d799-4a15-ab4b-349619ba0dd1"
Parent: "f3e12c5d-f4f3-4676-96ce-280afc99f2cd"
Template: "f3e12c5d-f4f3-4676-96ce-280afc99f2cd"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Text and Image Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {8406EACE-CA58-4190-9269-A04B1C9504DA}
    {F3E12C5D-F4F3-4676-96CE-280AFC99F2CD}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "be6205e2-841b-4430-bf1f-f2dc1517cb2b"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240220T150148Z
