---
ID: "34321060-ff25-4267-aa47-de8a60fcb1da"
Parent: "b156657c-5ab4-4342-bd36-21b88b909204"
Template: "b156657c-5ab4-4342-bd36-21b88b909204"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Rendering Parameters/Link/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e7487ed4-feb8-483f-9beb-49adab5ba35d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240216T205039Z
