---
ID: "0c4fbe18-489a-418a-8f68-0e37ffa63da3"
Parent: "0e05beda-d28e-4242-acda-86190bbcd719"
Template: "0e05beda-d28e-4242-acda-86190bbcd719"
Path: /sitecore/templates/Feature/Selections/Admin/ScoreCards/ScoreCardDetail/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "13217b19-a3eb-433b-b299-06865cb2867a"
      Hint: ApplicationLabel
      Value: Application
    - ID: "13a119a4-5a4f-43ce-aab3-cd95148a6e2b"
      Hint: TitleLabel
      Value: Score Card Detail
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230105T001513Z
    - ID: "35937293-4a31-4e01-8a87-a823f936f5c3"
      Hint: ReviewsLabel
      Value: Reviews
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\iva@sitecore.net
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\iva@sitecore.net
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "30766dd5-7dd7-4b7c-96bf-990a3b893eb6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\iva@sitecore.net
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230105T120253Z
