---
ID: "c81d9919-2ea8-4e1b-88f8-5d2ad83779b6"
Parent: "108ba97b-169e-4502-b116-f9a2dc872456"
Template: "108ba97b-169e-4502-b116-f9a2dc872456"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Rendering Parameters/Venue/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "9f06ad43-aa59-43b6-9680-2198678e087d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\U0zm6N0Wat
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240307T134532Z
