---
ID: "5280f5d0-5552-4113-b951-8c5213bcaad3"
Parent: "8e84def2-fad3-401b-844f-6efa81d09def"
Template: "8e84def2-fad3-401b-844f-6efa81d09def"
Path: /sitecore/templates/Project/Sugcon2024/List Components/Rendering Parameters/Event Teaser/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240223T133021Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3a3c04a7-bf65-40ca-a061-82a2f750ee5e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240223T133021Z
