---
ID: "3834783e-6eaa-420d-8f89-028d0c511a36"
Parent: "f5d59b30-223d-4e5a-967d-19daf7934db6"
Template: "f5d59b30-223d-4e5a-967d-19daf7934db6"
Path: /sitecore/templates/Project/Sugcon2024/Generic Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {F5D59B30-223D-4E5A-967D-19DAF7934DB6}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {A87A00B1-E6DB-45AB-8B54-636FEC3B5523}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240105T121329Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\sebastian.winter@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\sebastian.winter@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "04ba73d3-9653-4e89-96b4-873381047216"
    - ID: "b0c01040-9941-4a8f-8400-b274c377885e"
      Hint: Title
      Value: $name
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240206T160336Z
