---
ID: "ddaa9fb1-68b7-409d-b412-c7bf9f8b333d"
Parent: "bdb05878-8135-4e8d-a094-eb2db3e4526b"
Template: "bdb05878-8135-4e8d-a094-eb2db3e4526b"
Path: /sitecore/templates/Feature/Selections/Admin/CountriesOverview/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220826T192756Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\iva@sitecore.net
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\iva@sitecore.net
    - ID: "8c1e5603-1e6f-4213-8252-b488364bafa3"
      Hint: TitleLabel
      Value: Countries
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "8c88ae5b-575c-49b5-bfa1-99092731b44b"
    - ID: "a3646705-21db-49a0-9961-d26dbedeaef6"
      Hint: OperationsTableHeader
      Value: Operations
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\iva@sitecore.net
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20220826T192825Z
    - ID: "fe31951d-905d-4ee2-a1bf-0bf5a0e36a56"
      Hint: NameTableHeader
      Value: Name
