---
ID: "3fbb1632-051b-4719-8ae7-02846b11a7f8"
Parent: "3035b703-6686-4588-846c-225ff737efe0"
Template: "3035b703-6686-4588-846c-225ff737efe0"
Path: /sitecore/templates/Project/Sugcon2024/List Components/Rendering Parameters/Speakers Grid/__Standard Values
