---
ID: "76533823-a4f8-4727-97ef-b5e376e34153"
Parent: "835ffae1-5cb1-46ea-b7da-f1915bb51a93"
Template: "835ffae1-5cb1-46ea-b7da-f1915bb51a93"
Path: /sitecore/templates/Feature/BehavioralPersonalization/Profile/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: apps/32x32/account.png
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{D1F0E3F3-D45C-4BD4-AD2C-17A56E7D0E1D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240202T162353Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Y6cPXOeDwf
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Y6cPXOeDwf
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "91599f55-d2f3-436b-922e-2bcd76bd7464"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Y6cPXOeDwf
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240202T174342Z
    - ID: "db72e0e4-6c9c-40ab-8943-38a3de733324"
      Hint: Name
      Value: $name
