---
ID: "f87324c7-dc29-4d71-b514-7b49e5534ee9"
Parent: "9813d24f-4506-43ed-b5c9-4f8033fca9e2"
Template: "9813d24f-4506-43ed-b5c9-4f8033fca9e2"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Accordion Element/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "077242f3-20e7-4fec-9309-9337edd815f5"
      Hint: Title
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240314T055711Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\x3rLvWVVyq
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\x3rLvWVVyq
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "2b37929c-77c9-41ec-a044-5ad532c86958"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240318T191128Z
