---
ID: "824631a6-fd81-475a-a3fa-56471432aec2"
Parent: "257a55ed-a2c1-4f5f-b369-23cdf02bde0b"
Template: "257a55ed-a2c1-4f5f-b369-23cdf02bde0b"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Event Teaser Folder/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
