---
ID: "63c83c2d-2a77-44b4-9c91-86949aaa8927"
Parent: "f220eb4b-7c0b-4c8b-8ef9-552684625ba1"
Template: "f220eb4b-7c0b-4c8b-8ef9-552684625ba1"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Rendering Parameters/Error Message/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ec1f8828-ae8e-47ff-baac-f7b2a782c550"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240319T164254Z
