---
ID: "1659ffdd-b675-4d93-9cc0-7998b8e6868d"
Parent: "3caa9812-e5cf-488e-9546-ecaa263c8a14"
Template: "3caa9812-e5cf-488e-9546-ecaa263c8a14"
Path: /sitecore/templates/Project/Sugcon2024/Sponsors/Sponsor/__Standard Values
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: Applications/16x16/star_green.png
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240228T141232Z
    - ID: "3d19f996-77c2-4fdd-a4ca-390fc5a12e56"
      Hint: SponsorName
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\U0zm6N0Wat
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\U0zm6N0Wat
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4c0e0aba-4b47-42a6-9ccb-3d38cbb96b09"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\U0zm6N0Wat
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240228T141521Z
