---
ID: "b1d7c47e-976f-480f-85d0-de48f6bbdd81"
Parent: "489433f5-e659-4912-9511-119d3f9acd8a"
Template: "489433f5-e659-4912-9511-119d3f9acd8a"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Hero Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {92AD7A66-1B2C-4B15-844B-ACCC4219323D}
    {489433F5-E659-4912-9511-119D3F9ACD8A}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "39d7cb7c-06f3-4e7a-9ff8-120e591c177c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240125T183403Z
