---
ID: "9f50ce35-811a-4e30-af7c-9adab40a5b2a"
Parent: "dc5cea84-31d9-4559-a9ee-9256b0c8ac0e"
Template: "dc5cea84-31d9-4559-a9ee-9256b0c8ac0e"
Path: /sitecore/templates/Project/Sugcon2024/List Components/Accordion Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {89F532D4-C6A3-4648-94BD-71D169E6C5C7}
    {9813D24F-4506-43ED-B5C9-4F8033FCA9E2}
    {DC5CEA84-31D9-4559-A9EE-9256B0C8AC0E}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240223T133021Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4844c869-d417-4a31-ae3b-8518883dae20"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UOUBIWQRx7
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240318T191601Z
