name: Build a Nextjs Application

on:
  workflow_call:
    inputs:
      workingDirectory:
        required: true
        type: string
    secrets:
      SITECORE_EDGE_CONTEXT_ID:
        required: true

jobs:

  build:
    name: Build the NextJs Application
    runs-on: ubuntu-latest
    env:
      GENERATE_STATIC_PATHS: false
      SITECORE_EDGE_CONTEXT_ID: ${{ secrets.SITECORE_EDGE_CONTEXT_ID }}
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 22.11.0
    - run: npm install
    - run: npm run build
    - run: npm run lint